---
apiVersion: v1
kind: Service
metadata:
  name: hello-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/hello"
spec:
  selector:
    app:  hello-backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
